# Generated by Django 4.1.7 on 2023-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_item_order_table_alter_category_slug_orderitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
