# Generated by Django 4.1.7 on 2023-03-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.IntegerField(
                choices=[(0, "message"), (1, "order"), (2, "comment")]
            ),
        ),
    ]
