# Generated by Django 4.1.7 on 2023-03-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
